2019-11-30 16:39:53.728 - [Info] MITM Version: 1.26
2019-11-30 16:39:53.743 - [Info] Auto Access Enabled: true
2019-11-30 16:39:53.744 - [Debug] [Init] Auto Access Barrier: true
2019-11-30 16:39:53.800 - [Info] SSH man-in-the-middle server for 172.20.0.5 listening on 0.0.0.0:10104
2019-11-30 16:39:54.240 - [Debug] [Connection] Attacker connected: 193.188.22.188 | Client Identification: SSH-2.0-libssh2_1.7.0
2019-11-30 16:39:54.322 - [Debug] [Connection] Client error on ssh server
2019-11-30 16:39:54.325 - [Debug] [Connection] Attacker closed the connection
2019-11-30 16:57:47.793 - [Debug] [Connection] Attacker connected: 120.132.2.135 | Client Identification: SSH-2.0-libssh-0.6.3
2019-11-30 16:57:49.374 - [Debug] [Auth] Attacker 120.132.2.135 trying to authenticate with "password"
2019-11-30 16:57:49.375 - [Debug] [Auto Access] Attacker: 120.132.2.135, Threshold: 1, Attempts: 1
2019-11-30 16:57:49.376 - [Debug] [Auto Access] Compromising the honeypot
2019-11-30 16:57:49.376 - [Debug] [Auto Access] Adding the following credentials: "test:california"
2019-11-30 16:57:49.592 - [Debug] [Auth] Valid credentials - Password Authentication
2019-11-30 16:57:49.592 - [Debug] [LXC] Attempting to connect to the honeypot: 172.20.0.5
2019-11-30 16:57:49.640 - [Debug] [LXC-Auth] Attacker authenticated and is inside container
2019-11-30 16:57:50.669 - [Debug] [Connection] Attacker connected: 120.132.2.135 | Client Identification: SSH-2.0-libssh-0.6.3
2019-11-30 16:57:52.325 - [Debug] [Auth] Attacker 120.132.2.135 trying to authenticate with "password"
2019-11-30 16:57:52.326 - [Debug] [Auth] Attacker authentication error: Invalid credentials - User does not exist
2019-11-30 16:57:52.327 - [Debug] [Auth] Attacker: 120.132.2.135 has so far made 1 attempts. Remaining: 5 attempts
2019-11-30 16:57:52.843 - [Debug] [Connection] Attacker closed the connection
2019-11-30 16:57:53.338 - [Debug] [EXEC] Noninteractive mode attacker command: cat /proc/cpuinfo | grep name | wc -l
