2019-11-27 18:26:32.031 - [Info] MITM Version: 1.26
2019-11-27 18:26:32.037 - [Info] Auto Access Enabled: true
2019-11-27 18:26:32.037 - [Debug] [Init] Auto Access Barrier: true
2019-11-27 18:26:32.058 - [Info] SSH man-in-the-middle server for 172.20.0.4 listening on 0.0.0.0:10103
2019-11-27 18:40:27.731 - [Debug] [Connection] Attacker connected: 104.148.119.2 | Client Identification: SSH-2.0-OpenSSH
2019-11-27 18:40:28.484 - [Debug] [Connection] Attacker closed the connection
2019-11-27 18:49:10.458 - [Debug] [Connection] Attacker connected: 190.153.249.99 | Client Identification: SSH-2.0-libssh-0.6.3
2019-11-27 18:49:11.517 - [Debug] [Auth] Attacker 190.153.249.99 trying to authenticate with "password"
2019-11-27 18:49:11.518 - [Debug] [Auto Access] Attacker: 190.153.249.99, Threshold: 1, Attempts: 1
2019-11-27 18:49:11.518 - [Debug] [Auto Access] Compromising the honeypot
2019-11-27 18:49:11.518 - [Debug] [Auto Access] Adding the following credentials: "root:p4$$w0rd12345678"
2019-11-27 18:49:11.674 - [Debug] [Auth] Valid credentials - Password Authentication
2019-11-27 18:49:11.674 - [Debug] [LXC] Attempting to connect to the honeypot: 172.20.0.4
2019-11-27 18:49:11.729 - [Debug] [LXC-Auth] Attacker authenticated and is inside container
2019-11-27 18:49:12.483 - [Debug] [Connection] Attacker connected: 190.153.249.99 | Client Identification: SSH-2.0-libssh-0.6.3
2019-11-27 18:49:13.676 - [Debug] [Auth] Attacker 190.153.249.99 trying to authenticate with "password"
2019-11-27 18:49:13.676 - [Debug] [Auth] Attacker authentication error: Invalid credentials - User does not exist
2019-11-27 18:49:13.677 - [Debug] [Auth] Attacker: 190.153.249.99 has so far made 1 attempts. Remaining: 5 attempts
2019-11-27 18:49:14.085 - [Debug] [Connection] Attacker closed the connection
2019-11-27 18:49:14.387 - [Debug] [EXEC] Noninteractive mode attacker command: cat /proc/cpuinfo | grep name | wc -l
