2019-11-12 18:12:12.421 - [Info] MITM Version: 1.26
2019-11-12 18:12:12.427 - [Info] Auto Access Enabled: true
2019-11-12 18:12:12.428 - [Debug] [Init] Auto Access Barrier: true
2019-11-12 18:12:12.451 - [Info] SSH man-in-the-middle server for 172.20.0.4 listening on 0.0.0.0:10103
2019-11-12 18:12:51.340 - [Debug] [Connection] Attacker connected: 5.152.159.31 | Client Identification: SSH-2.0-libssh-0.6.3
2019-11-12 18:12:52.076 - [Debug] [Auth] Attacker 5.152.159.31 trying to authenticate with "password"
2019-11-12 18:12:52.077 - [Debug] [Auto Access] Attacker: 5.152.159.31, Threshold: 1, Attempts: 1
2019-11-12 18:12:52.077 - [Debug] [Auto Access] Compromising the honeypot
2019-11-12 18:12:52.077 - [Debug] [Auto Access] Adding the following credentials: "mysql:messenger"
2019-11-12 18:12:52.285 - [Debug] [Auth] Valid credentials - Password Authentication
2019-11-12 18:12:52.286 - [Debug] [LXC] Attempting to connect to the honeypot: 172.20.0.4
2019-11-12 18:12:52.334 - [Debug] [LXC-Auth] Attacker authenticated and is inside container
2019-11-12 18:12:52.804 - [Debug] [Connection] Attacker connected: 5.152.159.31 | Client Identification: SSH-2.0-libssh-0.6.3
2019-11-12 18:12:53.538 - [Debug] [Auth] Attacker 5.152.159.31 trying to authenticate with "password"
2019-11-12 18:12:53.538 - [Debug] [Auth] Attacker authentication error: Invalid credentials - User does not exist
2019-11-12 18:12:53.539 - [Debug] [Auth] Attacker: 5.152.159.31 has so far made 1 attempts. Remaining: 5 attempts
2019-11-12 18:12:53.798 - [Debug] [Connection] Attacker closed the connection
2019-11-12 18:12:54.015 - [Debug] [EXEC] Noninteractive mode attacker command: cat /proc/cpuinfo | grep name | wc -l
2019-11-12 18:14:14.629 - [Debug] [Connection] Attacker closed connection
2019-11-12 18:14:14.638 - [Debug] [LXC] Container's OpenSSH server ended connection
2019-11-12 18:14:14.648 - [Debug] [LXC] Container's OpenSSH server closed connection
