2019-11-22 19:38:45.653 - [Info] MITM Version: 1.26
2019-11-22 19:38:45.663 - [Info] Auto Access Enabled: true
2019-11-22 19:38:45.664 - [Debug] [Init] Auto Access Barrier: true
2019-11-22 19:38:45.736 - [Info] SSH man-in-the-middle server for 172.20.0.5 listening on 0.0.0.0:10104
2019-11-22 20:12:10.142 - [Debug] [Connection] Attacker connected: 71.6.232.6 | Client Identification: SSH-2.0-OpenSSH_6.6.1
2019-11-22 20:12:19.209 - [Debug] [Connection] Attacker closed the connection
2019-11-22 20:25:53.097 - [Debug] [Connection] Attacker connected: 45.55.15.134 | Client Identification: SSH-2.0-libssh-0.6.3
2019-11-22 20:25:53.622 - [Debug] [Auth] Attacker 45.55.15.134 trying to authenticate with "password"
2019-11-22 20:25:53.624 - [Debug] [Auto Access] Attacker: 45.55.15.134, Threshold: 1, Attempts: 1
2019-11-22 20:25:53.624 - [Debug] [Auto Access] Compromising the honeypot
2019-11-22 20:25:53.625 - [Debug] [Auto Access] Adding the following credentials: "guest:ketan"
2019-11-22 20:25:54.038 - [Debug] [Auth] Valid credentials - Password Authentication
2019-11-22 20:25:54.039 - [Debug] [LXC] Attempting to connect to the honeypot: 172.20.0.5
2019-11-22 20:25:54.113 - [Debug] [LXC-Auth] Attacker authenticated and is inside container
2019-11-22 20:25:54.449 - [Debug] [Connection] Attacker connected: 45.55.15.134 | Client Identification: SSH-2.0-libssh-0.6.3
2019-11-22 20:25:54.971 - [Debug] [Auth] Attacker 45.55.15.134 trying to authenticate with "password"
2019-11-22 20:25:54.972 - [Debug] [Auth] Attacker authentication error: Invalid credentials - User does not exist
2019-11-22 20:25:54.973 - [Debug] [Auth] Attacker: 45.55.15.134 has so far made 1 attempts. Remaining: 5 attempts
2019-11-22 20:25:55.158 - [Debug] [Connection] Attacker closed the connection
2019-11-22 20:25:55.303 - [Debug] [EXEC] Noninteractive mode attacker command: cat /proc/cpuinfo | grep name | wc -l
