2019-11-15 17:38:48.934 - [Info] MITM Version: 1.26
2019-11-15 17:38:48.947 - [Info] Auto Access Enabled: true
2019-11-15 17:38:48.948 - [Debug] [Init] Auto Access Barrier: true
2019-11-15 17:38:48.974 - [Info] SSH man-in-the-middle server for 172.20.0.3 listening on 0.0.0.0:10102
2019-11-15 17:56:05.108 - [Debug] [Connection] Attacker connected: 62.231.7.221 | Client Identification: SSH-2.0-libssh-0.1
2019-11-15 17:56:05.249 - [Debug] [Connection] Attacker closed the connection
2019-11-15 18:08:42.596 - [Debug] [Connection] Attacker connected: 129.226.122.195 | Client Identification: SSH-2.0-libssh-0.6.3
2019-11-15 18:08:44.085 - [Debug] [Auth] Attacker 129.226.122.195 trying to authenticate with "password"
2019-11-15 18:08:44.086 - [Debug] [Auto Access] Attacker: 129.226.122.195, Threshold: 1, Attempts: 1
2019-11-15 18:08:44.086 - [Debug] [Auto Access] Compromising the honeypot
2019-11-15 18:08:44.086 - [Debug] [Auto Access] Adding the following credentials: "root:Pierre2017"
2019-11-15 18:08:44.231 - [Debug] [Auth] Valid credentials - Password Authentication
2019-11-15 18:08:44.231 - [Debug] [LXC] Attempting to connect to the honeypot: 172.20.0.3
2019-11-15 18:08:44.289 - [Debug] [LXC-Auth] Attacker authenticated and is inside container
2019-11-15 18:08:45.291 - [Debug] [Connection] Attacker connected: 129.226.122.195 | Client Identification: SSH-2.0-libssh-0.6.3
2019-11-15 18:08:46.838 - [Debug] [Auth] Attacker 129.226.122.195 trying to authenticate with "password"
2019-11-15 18:08:46.839 - [Debug] [Auth] Attacker authentication error: Invalid credentials - User does not exist
2019-11-15 18:08:46.840 - [Debug] [Auth] Attacker: 129.226.122.195 has so far made 1 attempts. Remaining: 5 attempts
2019-11-15 18:08:47.370 - [Debug] [Connection] Attacker closed the connection
2019-11-15 18:08:47.840 - [Debug] [EXEC] Noninteractive mode attacker command: cat /proc/cpuinfo | grep name | wc -l
