2019-11-20 19:16:35.868 - [Info] MITM Version: 1.26
2019-11-20 19:16:35.875 - [Info] Auto Access Enabled: true
2019-11-20 19:16:35.875 - [Debug] [Init] Auto Access Barrier: true
2019-11-20 19:16:35.899 - [Info] SSH man-in-the-middle server for 172.20.0.5 listening on 0.0.0.0:10104
2019-11-20 19:40:14.745 - [Debug] [Connection] Attacker connected: 104.148.119.2 | Client Identification: SSH-2.0-OpenSSH
2019-11-20 19:40:15.029 - [Debug] [Connection] Attacker closed the connection
2019-11-20 20:17:19.749 - [Debug] [Connection] Attacker connected: 51.68.126.142 | Client Identification: SSH-2.0-libssh-0.6.3
2019-11-20 20:17:20.309 - [Debug] [Auth] Attacker 51.68.126.142 trying to authenticate with "password"
2019-11-20 20:17:20.311 - [Debug] [Auto Access] Attacker: 51.68.126.142, Threshold: 1, Attempts: 1
2019-11-20 20:17:20.311 - [Debug] [Auto Access] Compromising the honeypot
2019-11-20 20:17:20.311 - [Debug] [Auto Access] Adding the following credentials: "moule:moule"
2019-11-20 20:17:20.641 - [Debug] [Auth] Valid credentials - Password Authentication
2019-11-20 20:17:20.641 - [Debug] [LXC] Attempting to connect to the honeypot: 172.20.0.5
2019-11-20 20:17:20.700 - [Debug] [LXC-Auth] Attacker authenticated and is inside container
2019-11-20 20:17:21.054 - [Debug] [Connection] Attacker connected: 51.68.126.142 | Client Identification: SSH-2.0-libssh-0.6.3
2019-11-20 20:17:21.612 - [Debug] [Auth] Attacker 51.68.126.142 trying to authenticate with "password"
2019-11-20 20:17:21.613 - [Debug] [Auth] Attacker authentication error: Invalid credentials - User does not exist
2019-11-20 20:17:21.614 - [Debug] [Auth] Attacker: 51.68.126.142 has so far made 1 attempts. Remaining: 5 attempts
2019-11-20 20:17:21.808 - [Debug] [Connection] Attacker closed the connection
2019-11-20 20:17:21.968 - [Debug] [EXEC] Noninteractive mode attacker command: cat /proc/cpuinfo | grep name | wc -l
